set(MODULE_SOURCE_DIR "pugixml")
set(MODULE_NEED_INSTALL TRUE)
set(MODULE_INSTALL_DIR "PugiXML")
set(PREBUILD_CONFIGURATIONS "Release" "Debug" "RelWithDebInfo")

set(MODULE_CONFIG_ARGS
    -DPUGIXML_USE_POSTFIX=ON
    -DPUGIXML_BUILD_TESTS=OFF
    -DPUGIXML_INSTALL=ON
)
