set(EGO_DEFAULT_RENDER_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(ego_default_render_config_assets)
    set(EGO_DEFAULT_RENDER_ASSETS_DIR "${EGO_DEFAULT_RENDER_DIR}/Assets")
    set(EGO_DEFAULT_RENDER_CONFIG_FILE "DefaultRender.xml")
    set(EGO_DEFAULT_RENDER_CONFIG_TEMPLATE "${EGO_DEFAULT_RENDER_DIR}/DefaultRender.xml.tpl")
    set(EGO_DEFAULT_RENDER_INSTALL_DIR "Plugins/Render")
    set(EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR "Assets")

    set(TPL_DEFAULT_RENDER_DEBUG_POINT_VERTEX_SHADER "${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/PointVS.hlsl")
    set(TPL_DEFAULT_RENDER_DEBUG_POINT_PIXEL_SHADER "${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/PointPS.hlsl")
    set(TPL_DEFAULT_RENDER_DEBUG_LINE_VERTEX_SHADER "${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/LineVS.hlsl")
    set(TPL_DEFAULT_RENDER_DEBUG_LINE_PIXEL_SHADER "${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/LinePS.hlsl")

    configure_file(
        "${EGO_DEFAULT_RENDER_CONFIG_TEMPLATE}"
        "${CMAKE_CURRENT_BINARY_DIR}/${EGO_DEFAULT_RENDER_CONFIG_FILE}.in"
        @ONLY
    )
    file(GENERATE
        OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/${EGO_DEFAULT_RENDER_CONFIG_FILE}"
        INPUT "${CMAKE_CURRENT_BINARY_DIR}/${EGO_DEFAULT_RENDER_CONFIG_FILE}.in"
    )

    add_custom_command(
        TARGET EgoDefaultRender
        POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory
            "$<TARGET_FILE_DIR:EgoDefaultRender>/${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}"
        COMMAND ${CMAKE_COMMAND} -E copy_directory
            "${EGO_DEFAULT_RENDER_ASSETS_DIR}"
            "$<TARGET_FILE_DIR:EgoDefaultRender>/${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}"
        COMMAND ${CMAKE_COMMAND} -E remove -f
            "$<TARGET_FILE_DIR:EgoDefaultRender>/${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/${EGO_DEFAULT_RENDER_CONFIG_FILE}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/${EGO_DEFAULT_RENDER_CONFIG_FILE}"
            "$<TARGET_FILE_DIR:EgoDefaultRender>/${EGO_DEFAULT_RENDER_CONFIG_FILE}"
    )

    install(
        DIRECTORY "${EGO_DEFAULT_RENDER_ASSETS_DIR}"
        DESTINATION "${EGO_DEFAULT_RENDER_INSTALL_DIR}"
        OPTIONAL
    )

    install(CODE
        "file(MAKE_DIRECTORY \"\${CMAKE_INSTALL_PREFIX}/${EGO_DEFAULT_RENDER_INSTALL_DIR}\")
        file(REMOVE \"\${CMAKE_INSTALL_PREFIX}/${EGO_DEFAULT_RENDER_INSTALL_DIR}/${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/${EGO_DEFAULT_RENDER_CONFIG_FILE}\")
        set(TPL_DEFAULT_RENDER_DEBUG_POINT_VERTEX_SHADER \"${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/PointVS.hlsl\")
        set(TPL_DEFAULT_RENDER_DEBUG_POINT_PIXEL_SHADER \"${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/PointPS.hlsl\")
        set(TPL_DEFAULT_RENDER_DEBUG_LINE_VERTEX_SHADER \"${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/LineVS.hlsl\")
        set(TPL_DEFAULT_RENDER_DEBUG_LINE_PIXEL_SHADER \"${EGO_DEFAULT_RENDER_RUNTIME_ASSETS_DIR}/Shaders/DebugRender/LinePS.hlsl\")
        configure_file(
            \"${EGO_DEFAULT_RENDER_CONFIG_TEMPLATE}\"
            \"\${CMAKE_INSTALL_PREFIX}/${EGO_DEFAULT_RENDER_INSTALL_DIR}/${EGO_DEFAULT_RENDER_CONFIG_FILE}\"
            @ONLY
        )"
    )
endfunction()
