#pragma once

#include "InputDevice.h"

namespace ego
{
    enum class KeyboardInputKey : InputDeviceKey
    {
        Cancel,
        Backspace,
        Tab,
        Clear,
        Enter,
        Pause,
        Escape,
        Space,
        PageUp,
        PageDown,
        End,
        Home,
        Left,
        Up,
        Right,
        Down,
        Select,
        Print,
        Execute,
        PrintScreen,
        Insert,
        Delete,
        Help,
        Number0,
        Number1,
        Number2,
        Number3,
        Number4,
        Number5,
        Number6,
        Number7,
        Number8,
        Number9,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Semicolon,
        Equal,
        Comma,
        Minus,
        Period,
        Slash,
        GraveAccent,
        LeftBracket,
        Backslash,
        RightBracket,
        Apostrophe,
        InternationalBackslash,
        CapsLock,
        ScrollLock,
        NumLock,
        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,
        LeftSystem,
        RightSystem,
        Menu,
        Sleep,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        NumpadMultiply,
        NumpadAdd,
        NumpadSeparator,
        NumpadSubtract,
        NumpadDecimal,
        NumpadDivide,
        NumpadEnter,
        NumpadEqual,
        BrowserBack,
        BrowserForward,
        BrowserRefresh,
        BrowserStop,
        BrowserSearch,
        BrowserFavorites,
        BrowserHome,
        VolumeMute,
        VolumeDown,
        VolumeUp,
        MediaNextTrack,
        MediaPreviousTrack,
        MediaStop,
        MediaPlayPause,
        LaunchMail,
        MediaSelect,
        LaunchApplication1,
        LaunchApplication2,
        KanaHangul,
        ImeOn,
        Junja,
        Final,
        HanjaKanji,
        ImeOff,
        Convert,
        NonConvert,
        Accept,
        ModeChange,
        Process,
        Packet,
        Count,
        Undefined = Count
    };

    inline constexpr InputDeviceKey KeyboardInputKeyCount = static_cast<InputDeviceKey>(KeyboardInputKey::Count);

    class KeyboardInputDevice : public InputDevice
    {
    public:
        KeyboardInputDevice();
        ~KeyboardInputDevice() override = default;

        InputDeviceType getType() const override;

        EGO_RTTI_VIRTUAL(KeyboardInputDevice, InputDevice);
    };

    EGO_POINTER(KeyboardInputDevice);
} // namespace ego
