set(EGO_DEFAULT_GUI_RENDER_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(ego_default_gui_render_config_assets)
    set(EGO_DEFAULT_GUI_RENDER_ASSETS_DIR "${EGO_DEFAULT_GUI_RENDER_DIR}/Assets")
    set(EGO_DEFAULT_GUI_RENDER_CONFIG_FILE "DefaultGuiRender.xml")
    set(EGO_DEFAULT_GUI_RENDER_CONFIG_TEMPLATE "${EGO_DEFAULT_GUI_RENDER_DIR}/DefaultGuiRender.xml.tpl")
    set(EGO_DEFAULT_GUI_RENDER_INSTALL_DIR "Plugins/GuiRender")
    set(EGO_DEFAULT_GUI_RENDER_RUNTIME_ASSETS_DIR "Assets")

    set(TPL_DEFAULT_GUI_RENDER_ASSETS_DIR "${EGO_DEFAULT_GUI_RENDER_ASSETS_DIR}")

    configure_file(
        "${EGO_DEFAULT_GUI_RENDER_CONFIG_TEMPLATE}"
        "${CMAKE_CURRENT_BINARY_DIR}/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}.in"
        @ONLY
    )
    file(GENERATE
        OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}"
        INPUT "${CMAKE_CURRENT_BINARY_DIR}/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}.in"
    )

    add_custom_command(
        TARGET EgoDefaultGuiRender
        POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}"
            "$<TARGET_FILE_DIR:EgoDefaultGuiRender>/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}"
    )

    install(
        DIRECTORY "${EGO_DEFAULT_GUI_RENDER_ASSETS_DIR}"
        DESTINATION "${EGO_DEFAULT_GUI_RENDER_INSTALL_DIR}"
        OPTIONAL
    )

    install(CODE
        "file(MAKE_DIRECTORY \"\${CMAKE_INSTALL_PREFIX}/${EGO_DEFAULT_GUI_RENDER_INSTALL_DIR}\")
        set(TPL_DEFAULT_GUI_RENDER_ASSETS_DIR \"${EGO_DEFAULT_GUI_RENDER_RUNTIME_ASSETS_DIR}\")
        configure_file(
            \"${EGO_DEFAULT_GUI_RENDER_CONFIG_TEMPLATE}\"
            \"\${CMAKE_INSTALL_PREFIX}/${EGO_DEFAULT_GUI_RENDER_INSTALL_DIR}/${EGO_DEFAULT_GUI_RENDER_CONFIG_FILE}\"
            @ONLY
        )"
    )
endfunction()
