include_guard()

set(EGO_CONFIGURATION_TYPES Debug Release Retail)
set(CMAKE_CONFIGURATION_TYPES ${EGO_CONFIGURATION_TYPES})

set(CMAKE_C_FLAGS_RETAIL ${CMAKE_C_FLAGS_RELEASE})
set(CMAKE_CXX_FLAGS_RETAIL ${CMAKE_CXX_FLAGS_RELEASE})
set(CMAKE_EXE_LINKER_FLAGS_RETAIL ${CMAKE_EXE_LINKER_FLAGS_RELEASE})
set(CMAKE_SHARED_LINKER_FLAGS_RETAIL ${CMAKE_SHARED_LINKER_FLAGS_RELEASE})

set(CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELWITHDEBINFO})
set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
set(CMAKE_EXE_LINKER_FLAGS_RELEASE ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO})
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE ${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO})

add_compile_definitions(
    EGO_CONFIG=$<CONFIG>
    EGO_CONFIG_NAME="$<CONFIG>"

    $<$<CONFIG:Debug>:EGO_CONFIG_DEBUG>
    $<$<CONFIG:Release>:EGO_CONFIG_RELEASE>
    $<$<CONFIG:Retail>:EGO_CONFIG_RETAIL>
)