include_guard()

set(EGO_BASE_CONFIGURATION_TYPES Debug Release Profile Retail)
set(EGO_ASAN_CONFIGURATION_TYPES DebugAsan ReleaseAsan ProfileAsan)
set(EGO_CONFIGURATION_TYPES ${EGO_BASE_CONFIGURATION_TYPES} ${EGO_ASAN_CONFIGURATION_TYPES})

if (CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_CONFIGURATION_TYPES ${EGO_CONFIGURATION_TYPES} CACHE STRING "Available build configurations." FORCE)
else()
    if (NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build configuration." FORCE)
    endif()

    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${EGO_CONFIGURATION_TYPES})
endif()

set(EGO_RELEASE_C_FLAGS "${CMAKE_C_FLAGS_RELEASE}")
set(EGO_RELEASE_CXX_FLAGS "${CMAKE_CXX_FLAGS_RELEASE}")
set(EGO_RELEASE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")
set(EGO_RELEASE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS_RELEASE}")
set(EGO_RELEASE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS_RELEASE}")

function(_ego_remove_ndebug_flag OUT_VAR FLAGS)
    set(RESULT "${FLAGS}")
    string(REPLACE "/DNDEBUG" "" RESULT "${RESULT}")
    string(REPLACE "/D NDEBUG" "" RESULT "${RESULT}")
    string(REPLACE "-DNDEBUG" "" RESULT "${RESULT}")
    string(REGEX REPLACE " +" " " RESULT "${RESULT}")
    string(STRIP "${RESULT}" RESULT)
    set(${OUT_VAR} "${RESULT}" PARENT_SCOPE)
endfunction()

function(_ego_remove_msvc_runtime_check_flags OUT_VAR FLAGS)
    set(RESULT "${FLAGS}")
    string(REPLACE "/RTC1" "" RESULT "${RESULT}")
    string(REPLACE "/RTCc" "" RESULT "${RESULT}")
    string(REPLACE "/RTCs" "" RESULT "${RESULT}")
    string(REPLACE "/RTCu" "" RESULT "${RESULT}")
    string(REPLACE "/ZI" "/Zi" RESULT "${RESULT}")
    string(REGEX REPLACE " +" " " RESULT "${RESULT}")
    string(STRIP "${RESULT}" RESULT)
    set(${OUT_VAR} "${RESULT}" PARENT_SCOPE)
endfunction()

function(_ego_setup_msvc_asan_link_flags OUT_VAR FLAGS)
    set(RESULT "${FLAGS}")
    string(REPLACE "/INCREMENTAL:YES" "" RESULT "${RESULT}")
    string(REPLACE "/INCREMENTAL:NO" "" RESULT "${RESULT}")
    string(REPLACE "/INCREMENTAL" "" RESULT "${RESULT}")
    string(REPLACE "/DEBUG" "" RESULT "${RESULT}")
    string(REGEX REPLACE " +" " " RESULT "${RESULT}")
    string(STRIP "${RESULT}" RESULT)
    string(APPEND RESULT " /INCREMENTAL:NO /DEBUG")
    set(${OUT_VAR} "${RESULT}" PARENT_SCOPE)
endfunction()

_ego_remove_ndebug_flag(EGO_RELEASE_ASSERT_C_FLAGS "${EGO_RELEASE_C_FLAGS}")
_ego_remove_ndebug_flag(EGO_RELEASE_ASSERT_CXX_FLAGS "${EGO_RELEASE_CXX_FLAGS}")

set(CMAKE_C_FLAGS_RELEASE "${EGO_RELEASE_ASSERT_C_FLAGS}")
set(CMAKE_CXX_FLAGS_RELEASE "${EGO_RELEASE_ASSERT_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${EGO_RELEASE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${EGO_RELEASE_SHARED_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${EGO_RELEASE_MODULE_LINKER_FLAGS}")

set(CMAKE_C_FLAGS_PROFILE "${EGO_RELEASE_C_FLAGS}")
set(CMAKE_CXX_FLAGS_PROFILE "${EGO_RELEASE_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_PROFILE "${EGO_RELEASE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_PROFILE "${EGO_RELEASE_SHARED_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_PROFILE "${EGO_RELEASE_MODULE_LINKER_FLAGS}")

set(CMAKE_C_FLAGS_RETAIL "${EGO_RELEASE_C_FLAGS}")
set(CMAKE_CXX_FLAGS_RETAIL "${EGO_RELEASE_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_RETAIL "${EGO_RELEASE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_RETAIL "${EGO_RELEASE_SHARED_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_RETAIL "${EGO_RELEASE_MODULE_LINKER_FLAGS}")

set(EGO_DEBUG_ASAN_C_FLAGS "${CMAKE_C_FLAGS_DEBUG}")
set(EGO_DEBUG_ASAN_CXX_FLAGS "${CMAKE_CXX_FLAGS_DEBUG}")
if (MSVC)
    _ego_remove_msvc_runtime_check_flags(EGO_DEBUG_ASAN_C_FLAGS "${EGO_DEBUG_ASAN_C_FLAGS}")
    _ego_remove_msvc_runtime_check_flags(EGO_DEBUG_ASAN_CXX_FLAGS "${EGO_DEBUG_ASAN_CXX_FLAGS}")
    string(APPEND EGO_DEBUG_ASAN_C_FLAGS " /fsanitize=address")
    string(APPEND EGO_DEBUG_ASAN_CXX_FLAGS " /fsanitize=address")
endif()

set(CMAKE_C_FLAGS_DEBUGASAN "${EGO_DEBUG_ASAN_C_FLAGS}")
set(CMAKE_CXX_FLAGS_DEBUGASAN "${EGO_DEBUG_ASAN_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_DEBUGASAN "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUGASAN "${CMAKE_SHARED_LINKER_FLAGS_DEBUG}")
set(CMAKE_MODULE_LINKER_FLAGS_DEBUGASAN "${CMAKE_MODULE_LINKER_FLAGS_DEBUG}")

set(EGO_RELEASE_ASAN_C_FLAGS "${EGO_RELEASE_ASSERT_C_FLAGS}")
set(EGO_RELEASE_ASAN_CXX_FLAGS "${EGO_RELEASE_ASSERT_CXX_FLAGS}")
set(EGO_PROFILE_ASAN_C_FLAGS "${EGO_RELEASE_C_FLAGS}")
set(EGO_PROFILE_ASAN_CXX_FLAGS "${EGO_RELEASE_CXX_FLAGS}")
if (MSVC)
    string(APPEND EGO_RELEASE_ASAN_C_FLAGS " /fsanitize=address")
    string(APPEND EGO_RELEASE_ASAN_CXX_FLAGS " /fsanitize=address")
    string(APPEND EGO_PROFILE_ASAN_C_FLAGS " /fsanitize=address")
    string(APPEND EGO_PROFILE_ASAN_CXX_FLAGS " /fsanitize=address")

    string(APPEND EGO_RELEASE_ASAN_C_FLAGS " /Zi")
    string(APPEND EGO_RELEASE_ASAN_CXX_FLAGS " /Zi")
    string(APPEND EGO_PROFILE_ASAN_C_FLAGS " /Zi")
    string(APPEND EGO_PROFILE_ASAN_CXX_FLAGS " /Zi")
endif()

set(CMAKE_C_FLAGS_RELEASEASAN "${EGO_RELEASE_ASAN_C_FLAGS}")
set(CMAKE_CXX_FLAGS_RELEASEASAN "${EGO_RELEASE_ASAN_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_RELEASEASAN "${EGO_RELEASE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASEASAN "${EGO_RELEASE_SHARED_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASEASAN "${EGO_RELEASE_MODULE_LINKER_FLAGS}")

set(CMAKE_C_FLAGS_PROFILEASAN "${EGO_PROFILE_ASAN_C_FLAGS}")
set(CMAKE_CXX_FLAGS_PROFILEASAN "${EGO_PROFILE_ASAN_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_PROFILEASAN "${EGO_RELEASE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_PROFILEASAN "${EGO_RELEASE_SHARED_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_PROFILEASAN "${EGO_RELEASE_MODULE_LINKER_FLAGS}")

if (MSVC)
    foreach(ASAN_CONFIGURATION IN LISTS EGO_ASAN_CONFIGURATION_TYPES)
        string(TOUPPER "${ASAN_CONFIGURATION}" ASAN_CONFIGURATION_KEY)
        _ego_setup_msvc_asan_link_flags(
            CMAKE_EXE_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}
            "${CMAKE_EXE_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}}"
        )
        _ego_setup_msvc_asan_link_flags(
            CMAKE_SHARED_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}
            "${CMAKE_SHARED_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}}"
        )
        _ego_setup_msvc_asan_link_flags(
            CMAKE_MODULE_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}
            "${CMAKE_MODULE_LINKER_FLAGS_${ASAN_CONFIGURATION_KEY}}"
        )
    endforeach()
endif()

add_compile_definitions(
    EGO_CONFIG=$<CONFIG>
    EGO_CONFIG_NAME="$<CONFIG>"
    EGO_MODULE_PLATFORM_NAME="$<PLATFORM_ID>"
    EGO_MODULE_CONFIGURATION_NAME="$<CONFIG>"
)

foreach(CONFIGURATION IN ITEMS Debug DebugAsan)
    add_compile_definitions(
        $<$<CONFIG:${CONFIGURATION}>:EGO_CONFIG_DEBUG>
    )
endforeach()

foreach(CONFIGURATION IN ITEMS Release ReleaseAsan)
    add_compile_definitions(
        $<$<CONFIG:${CONFIGURATION}>:EGO_CONFIG_RELEASE>
    )
endforeach()

foreach(CONFIGURATION IN ITEMS Profile ProfileAsan)
    add_compile_definitions(
        $<$<CONFIG:${CONFIGURATION}>:EGO_CONFIG_PROFILE>
    )
endforeach()

foreach(CONFIGURATION IN ITEMS Retail)
    add_compile_definitions(
        $<$<CONFIG:${CONFIGURATION}>:EGO_CONFIG_RETAIL>
    )
endforeach()

foreach(CONFIGURATION IN LISTS EGO_ASAN_CONFIGURATION_TYPES)
    add_compile_definitions(
        $<$<CONFIG:${CONFIGURATION}>:EGO_CONFIG_ASAN>
    )
endforeach()
