set(WinPixEventRuntime_ROOT "" CACHE PATH "Root directory of WinPixEventRuntime.")

set(WIN_PIX_BINARY_ARCH "")
if (CMAKE_VS_PLATFORM_NAME)
    set(WIN_PIX_BINARY_ARCH "${CMAKE_VS_PLATFORM_NAME}")
elseif (CMAKE_GENERATOR_PLATFORM)
    set(WIN_PIX_BINARY_ARCH "${CMAKE_GENERATOR_PLATFORM}")
elseif (DEFINED CMAKE_SIZEOF_VOID_P AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(WIN_PIX_BINARY_ARCH "x64")
endif()

set(WIN_PIX_ROOTS)
if (WinPixEventRuntime_ROOT)
    list(APPEND WIN_PIX_ROOTS "${WinPixEventRuntime_ROOT}")
endif()

foreach(WIN_PIX_ROOT_ENV_VAR IN ITEMS WinPixEventRuntime_ROOT WINPIX_EVENT_RUNTIME_ROOT)
    if (DEFINED ENV{${WIN_PIX_ROOT_ENV_VAR}})
        list(APPEND WIN_PIX_ROOTS "$ENV{${WIN_PIX_ROOT_ENV_VAR}}")
    endif()
endforeach()

ego_get_third_party_build_roots(WIN_PIX_BUILD_ROOTS)
foreach(WIN_PIX_BUILD_ROOT IN LISTS WIN_PIX_BUILD_ROOTS)
    list(APPEND WIN_PIX_ROOTS "${WIN_PIX_BUILD_ROOT}/WinPixEventRuntime")
endforeach()

ego_third_party_resolve_path("WinPixEventRuntime" WIN_PIX_BUNDLED_ROOT)
list(APPEND WIN_PIX_ROOTS "${WIN_PIX_BUNDLED_ROOT}")
list(REMOVE_DUPLICATES WIN_PIX_ROOTS)

set(WIN_PIX_BINARY_SUFFIXES)
if (WIN_PIX_BINARY_ARCH)
    list(APPEND WIN_PIX_BINARY_SUFFIXES
        "Bin/${WIN_PIX_BINARY_ARCH}"
        "bin/${WIN_PIX_BINARY_ARCH}"
    )
endif()

find_path(
    EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_INCLUDE_DIR
    NAMES WinPixEventRuntime/pix3.h
    PATHS ${WIN_PIX_ROOTS}
    PATH_SUFFIXES Include include
    NO_DEFAULT_PATH
)

find_library(
    EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_LIBRARY_FILE
    NAMES WinPixEventRuntime
    PATHS ${WIN_PIX_ROOTS}
    PATH_SUFFIXES ${WIN_PIX_BINARY_SUFFIXES}
    NO_DEFAULT_PATH
)

find_file(
    EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_RUNTIME_FILE
    NAMES WinPixEventRuntime.dll
    PATHS ${WIN_PIX_ROOTS}
    PATH_SUFFIXES ${WIN_PIX_BINARY_SUFFIXES}
    NO_DEFAULT_PATH
)

if (EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_INCLUDE_DIR
    AND EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_LIBRARY_FILE
    AND EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_RUNTIME_FILE
)
    ego_third_party_create_binary_target(
        WinPixEventRuntime
        "${EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_INCLUDE_DIR}"
        "${EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_LIBRARY_FILE}"
        "${EGO_THIRD_PARTY_WINPIXEVENTRUNTIME_RUNTIME_FILE}"
    )
    set(EGO_THIRD_PARTY_FOUND TRUE)
endif()
